apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: edilmar/gitopsfc
  newTag: 6de3e224275a96616370d4717979e292d8da200e
